USE DATABASE CARD_TRANSACTION;

CREATE OR REPLACE TABLE SILVER.TRANSACTIONS_STRUCTURED AS
SELECT 
    TRANS_NUM,
    CC_NUM,
    TRANS_DATE_TRANS_TIME AS TRANSACTION_TIMESTAMP,
    AMT AS AMOUNT,
    UPPER(TRIM(MERCHANT)) AS MERCHANT_CLEAN,
    UPPER(TRIM(CATEGORY)) AS CATEGORY_CLEAN,
    IS_FRAUD,
    CASE 
        WHEN IS_FRAUD = 1 THEN 'FRAUD'
        ELSE 'LEGITIMATE' 
    END AS TRANSACTION_TYPE
FROM CARD_TRANSACTION.BRONZE.RAW_TRANSACTIONS;