-- 02_silver/rebeca/02_enhanced_features.sql
-- Features avanzados para análisis
USE DATABASE CARD_TRANSACTION;

CREATE OR REPLACE TABLE SILVER.TRANSACTIONS_ENHANCED AS
SELECT 
    *,
    HOUR(TRANSACTION_TIMESTAMP) AS HOUR_OF_DAY,
    DAYOFWEEK(TRANSACTION_TIMESTAMP) AS DAY_OF_WEEK,
    MONTH(TRANSACTION_TIMESTAMP) AS MONTH_OF_YEAR,
    CASE 
        WHEN AMOUNT < 10 THEN 'VERY_LOW'
        WHEN AMOUNT < 50 THEN 'LOW'
        WHEN AMOUNT < 200 THEN 'MEDIUM'
        WHEN AMOUNT < 1000 THEN 'HIGH'
        ELSE 'VERY_HIGH'
    END AS AMOUNT_CATEGORY
FROM SILVER.TRANSACTIONS_STRUCTURED;