-- Validaciones básicas de calidad
SELECT COUNT(*) FROM SILVER.TRANSACTIONS_ENHANCED;
SELECT COUNT(*) FROM SILVER.DIM_MERCHANTS;

-- Distribución de fraudes
SELECT 
    TRANSACTION_TYPE,
    COUNT(*) as count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) as percentage
FROM SILVER.TRANSACTIONS_ENHANCED
GROUP BY TRANSACTION_TYPE;