USE SCHEMA card_transaction.bronze;

CREATE OR REPLACE TABLE RAW_TRANSACTIONS_TEST (
    INDEX_ID INT,
    TRANS_DATE_TRANS_TIME TIMESTAMP_NTZ, 
    CC_NUM VARCHAR,             
    MERCHANT VARCHAR,
    CATEGORY VARCHAR,
    AMT FLOAT,
    FIRST_NAME VARCHAR,         
    LAST_NAME VARCHAR,          
    GENDER VARCHAR,
    STREET VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    ZIP VARCHAR,                
    LAT FLOAT,
    LONG FLOAT,
    CITY_POP INT,
    JOB VARCHAR,
    DOB DATE,
    TRANS_NUM VARCHAR,
    UNIX_TIME INT,
    MERCH_LAT FLOAT,
    MERCH_LONG FLOAT,
    IS_FRAUD INT
);

COPY INTO RAW_TRANSACTIONS_TEST
FROM @stage_bronze
FILES = ('fraudTest.csv') -- <--- Aquí apuntamos al archivo de test
FILE_FORMAT = (
    TYPE = 'CSV' 
    SKIP_HEADER = 1 
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '')
    TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS' 
    DATE_FORMAT = 'YYYY-MM-DD'
)
ON_ERROR = 'CONTINUE';


SELECT COUNT(*) as rows_test 
FROM RAW_TRANSACTIONS_TEST;