-- 1. Configuración del Rol
USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS NOTEBOOK_ADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE NOTEBOOK_ADMIN;
GRANT MONITOR ON ACCOUNT TO ROLE NOTEBOOK_ADMIN;
GRANT ALL PRIVILEGES ON DATABASE card_transaction TO ROLE NOTEBOOK_ADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE card_transaction TO ROLE NOTEBOOK_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE NOTEBOOK_ADMIN;
GRANT USAGE ON WAREHOUSE SNOWFLAKE_LEARNING_WH TO ROLE NOTEBOOK_ADMIN;

-- 2. Creación de Usuarios (Solo si son nuevos)
CREATE USER IF NOT EXISTS rebeca
    PASSWORD = 'password123' 
    LOGIN_NAME = 'rebeca'
    FIRST_NAME = 'rebeca'
    DEFAULT_ROLE = NOTEBOOK_ADMIN
    MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS mario
    PASSWORD = 'password123' 
    LOGIN_NAME = 'mario'
    FIRST_NAME = 'mario'
    DEFAULT_ROLE = NOTEBOOK_ADMIN
    MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS contreras
    PASSWORD = 'password123' 
    LOGIN_NAME = 'contreras'
    FIRST_NAME = 'contreras'
    DEFAULT_ROLE = NOTEBOOK_ADMIN
    MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS salvador
    PASSWORD = 'password123' 
    LOGIN_NAME = 'salvador'
    FIRST_NAME = 'Maria' 
    DEFAULT_ROLE = NOTEBOOK_ADMIN
    MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS apolonio
    PASSWORD = 'password123' 
    LOGIN_NAME = 'apolonio'
    FIRST_NAME = 'apolonio'
    DEFAULT_ROLE = NOTEBOOK_ADMIN
    MUST_CHANGE_PASSWORD = TRUE;

-- 3. La "Fuerza" - Asignación y Actualización (Para nuevos Y existentes)
USE ROLE SECURITYADMIN;

-- 3a. Asegura que sean miembros del rol
GRANT ROLE NOTEBOOK_ADMIN TO USER rebeca;
GRANT ROLE NOTEBOOK_ADMIN TO USER mario;
GRANT ROLE NOTEBOOK_ADMIN TO USER contreras;
GRANT ROLE NOTEBOOK_ADMIN TO USER salvador;
GRANT ROLE NOTEBOOK_ADMIN TO USER apolonio;

-- 3b. Asegura que sea su rol por defecto al iniciar sesión
ALTER USER rebeca SET DEFAULT_ROLE = NOTEBOOK_ADMIN;
ALTER USER mario SET DEFAULT_ROLE = NOTEBOOK_ADMIN;
ALTER USER contreras SET DEFAULT_ROLE = NOTEBOOK_ADMIN;
ALTER USER salvador SET DEFAULT_ROLE = NOTEBOOK_ADMIN;
ALTER USER apolonio SET DEFAULT_ROLE = NOTEBOOK_ADMIN;