-- 1. Configuración del Rol
USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS NOTEBOOK_ADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE NOTEBOOK_ADMIN;
GRANT MONITOR ON ACCOUNT TO ROLE NOTEBOOK_ADMIN;
GRANT ALL PRIVILEGES ON DATABASE card_transaction TO ROLE NOTEBOOK_ADMIN;
-- 1. Permisos base de infraestructura (Warehouse y Cuenta)
GRANT MONITOR ON ACCOUNT TO ROLE NOTEBOOK_ADMIN; -- Opcional: permite ver historial de queries/créditos
-- 2. Permiso para "entrar" a la Base de Datos (sin poder borrarla)
GRANT USAGE ON DATABASE card_transaction TO ROLE NOTEBOOK_ADMIN;
-- 3. Permiso para "usar" los Esquemas (contenedores)
-- Existentes:
GRANT USAGE ON ALL SCHEMAS IN DATABASE card_transaction TO ROLE NOTEBOOK_ADMIN;
-- Futuros:
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE card_transaction TO ROLE NOTEBOOK_ADMIN;
-- 4. Permisos de Lectura y Escritura en Tablas (CRUD)
-- Existentes:
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE card_transaction TO ROLE NOTEBOOK_ADMIN;
-- Futuros (Automático para tablas nuevas):
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE card_transaction TO ROLE NOTEBOOK_ADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE card_transaction TO ROLE NOTEBOOK_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE NOTEBOOK_ADMIN;
GRANT USAGE ON WAREHOUSE SNOWFLAKE_LEARNING_WH TO ROLE NOTEBOOK_ADMIN;
GRANT USAGE ON INTEGRATION MY_GIT_API_INTEGRATION TO ROLE NOTEBOOK_ADMIN;
GRANT READ, WRITE ON GIT REPOSITORY card_transaction.public."TSID-Fraud-Detection" TO ROLE NOTEBOOK_ADMIN;


-- 2. Creación de Usuarios (Solo si son nuevos)
CREATE USER IF NOT EXISTS rebeca
    PASSWORD = 'password123' 
    LOGIN_NAME = 'rebeca'
    FIRST_NAME = 'rebeca'
    DEFAULT_ROLE = NOTEBOOK_ADMIN
    MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS mario
    PASSWORD = 'password123' 
    LOGIN_NAME = 'mario'
    FIRST_NAME = 'mario'
    DEFAULT_ROLE = NOTEBOOK_ADMIN
    MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS contreras
    PASSWORD = 'password123' 
    LOGIN_NAME = 'contreras'
    FIRST_NAME = 'contreras'
    DEFAULT_ROLE = NOTEBOOK_ADMIN
    MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS salvador
    PASSWORD = 'password123' 
    LOGIN_NAME = 'salvador'
    FIRST_NAME = 'Maria' 
    DEFAULT_ROLE = NOTEBOOK_ADMIN
    MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS apolonio
    PASSWORD = 'password123' 
    LOGIN_NAME = 'apolonio'
    FIRST_NAME = 'apolonio'
    DEFAULT_ROLE = NOTEBOOK_ADMIN
    MUST_CHANGE_PASSWORD = TRUE;

-- 3. La "Fuerza" - Asignación y Actualización (Para nuevos Y existentes)
USE ROLE SECURITYADMIN;

-- 3a. Asegura que sean miembros del rol
GRANT ROLE NOTEBOOK_ADMIN TO USER rebeca;
GRANT ROLE NOTEBOOK_ADMIN TO USER mario;
GRANT ROLE NOTEBOOK_ADMIN TO USER contreras;
GRANT ROLE NOTEBOOK_ADMIN TO USER salvador;
GRANT ROLE NOTEBOOK_ADMIN TO USER apolonio;

-- 3b. Asegura que sea su rol por defecto al iniciar sesión
ALTER USER rebeca SET DEFAULT_ROLE = NOTEBOOK_ADMIN;
ALTER USER mario SET DEFAULT_ROLE = NOTEBOOK_ADMIN;
ALTER USER contreras SET DEFAULT_ROLE = NOTEBOOK_ADMIN;
ALTER USER salvador SET DEFAULT_ROLE = NOTEBOOK_ADMIN;
ALTER USER apolonio SET DEFAULT_ROLE = NOTEBOOK_ADMIN;